### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by miwaniza** [mwydmuch/ZoomVideoComposer#1]
I found that using concurrent.futures increasing performance up to 10 times:

`    with ThreadPoolExecutor(max_workers=n_jobs) as executor:
        futures = [executor.submit(process_frame, i) for i in range(num_frames)]
        for _ in tqdm(concurrent.futures.as_completed(futures), total=num_frames):
            pass`

Instead of:
`    Parallel(n_jobs=n_jobs)(delayed(process_frame)(i) for i in trange(num_frames))`

**Comment by mwydmuch** [comment]
Great and thanks for opening the issue! Would you like to do a PR with this change?

**Comment by miwaniza** [comment]
Yes, PR would be great

**Comment by mwydmuch** [comment]
Cool! Waiting for your PR then :)

**Comment by miwaniza** [comment]
Done: #2

**Comment by miwaniza** [comment]
Also, I did some investigation, and using CUDA via [CuPy](https://cupy.dev/) in zoom_crop is not providing a dramatical increase in performance. Meanwhile, it requires certain steps to configure everything, so it's easier to stay with the CPU.

```python
import cupy as cp

def zoom_crop(image, zoom, resampling_func=Image.Resampling.LANCZOS):
    width, height = image.size
    zoom_width = width * zoom
    zoom_height = height * zoom
    image_data = cp.asarray(image)
    zoom_data = cp.zeros((int(zoom_height), int(zoom_width), 3), dtype=cp.uint8)
    for i in range(3):
        zoom_data[..., i] = cp.array(Image.fromarray(cp.asnumpy(image_data[..., i])).resize((int(zoom_width), int(zoom_height)), resampling_func))
    crop_data = zoom_data[
        int((zoom_height - height) / 2):int((zoom_height + height) / 2),
        int((zoom_width - width) / 2):int((zoom_width + width) / 2),
        :
    ]
    return Image.fromarray(cp.asnumpy(crop_data))
```

**Comment by mwydmuch** [comment]
Thank you for testing all of that, that's a very helpful! Yeah, I also think that it's good enough for the use case to just use CPU.
